### PR TITLE
check.rb - add require 'bundler/vendor/uri/lib/uri'

### PR DESCRIPTION
**Pull request by MSP-Greg**
README.md - add curl note

I grabbed a shortened URI of https://git.io/rg-ssl

### CODE REVIEW

**Comment by MSP-Greg** [comment]
@indirect

1. curl command works in Windows 10, but emoji may not render
2. `bundler/vendor/uri/lib/uri` is not autoloaded, so added back in

**Comment by indirect** [comment]
thanks!

**Comment by indirect** [comment]
@MSP-Greg I'm seeing this error:

```
bad argument (expected Bundler::URI object or Bundler::URI string)
```

**Comment by indirect** [comment]
ohhhhh I understand, calling `defined?(Bundler::URI)` doesn't trigger the autoload, so it doesn't get loaded, so it doesn't work. 🤦

**Pull request merged**
